services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: snatty
      POSTGRES_PASSWORD: snatty
      POSTGRES_DB: snatty
    ports:
      - "5432:5432"
    volumes:
      - snatty_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  snatty_pg_data:
